version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: priyanshujains/sb:latest
    container_name: backend
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/your-db

  frontend:
    image: priyanshujains/fr:latest
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
